services:

  app:
    container_name: find-me
    image: mertend/find-me:latest
    env_file:
      - .env
    networks:
      - web
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.find-me-router.rule=Host(`www.festival-find.me`) || Host(`festival-find.me`)
      - traefik.http.routers.find-me-router.entrypoints=websecure
      - traefik.http.routers.find-me-router.tls=true
      - traefik.http.routers.find-me-router.tls.certresolver=lets-encrypt
      - traefik.docker.network=web
      - com.centurylinklabs.watchtower.enable=true

networks:
  web:
    external: true
